# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_content',
            field=models.TextField(default='default'),
        ),
    ]
