# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20180208_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_content', models.TextField(default='default review')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('body', models.TextField()),
                ('sourceLogo', models.URLField()),
                ('sourceDomain', models.URLField()),
                ('originalLink', models.URLField(unique=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dailyposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
