# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title_1', models.CharField(max_length=100, unique=True)),
                ('sourceLogo_1', models.URLField()),
                ('sourceDomain_1', models.URLField()),
                ('originalLink_1', models.URLField(unique=True)),
                ('short_content_1', models.TextField(default='default review')),
                ('body_1', models.TextField()),
                ('title_2', models.CharField(max_length=100, unique=True)),
                ('sourceLogo_2', models.URLField()),
                ('sourceDomain_2', models.URLField()),
                ('originalLink_2', models.URLField(unique=True)),
                ('short_content_2', models.TextField(default='default review')),
                ('body_2', models.TextField()),
                ('title_3', models.CharField(max_length=100, unique=True)),
                ('sourceLogo_3', models.URLField()),
                ('sourceDomain_3', models.URLField()),
                ('originalLink_3', models.URLField(unique=True)),
                ('short_content_3', models.TextField(default='default review')),
                ('body_3', models.TextField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dailys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
