# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dailys_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailys',
            name='sourceDomain_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailys',
            name='sourceDomain_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailys',
            name='sourceDomain_3',
            field=models.CharField(max_length=200),
        ),
    ]
