# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180503_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
