
export const REQUEST_DAILYS = 'REQUEST_DAILYS';
export const RECEIVE_DAILYS = 'RECEIVE_DAILYS';

export const REQUEST_ABOUT = 'REQUEST_ABOUT';
export const RECEIVE_ABOUT = 'RECEIVE_ABOUT';

export const CHANGE_PATH = 'CHANGE_SELECTED_PATH';

export const REQUEST_DAILY_DETAIL = 'REQUEST_DAILY_DETAIL';
export const RECEIVE_DAILY_DETAIL = 'RECEIVE_DAILY_DETAIL';


