
export const REQUEST_BLOGS = 'REQUEST_BLOGS';
export const RECEIVE_BLOGS = 'RECEIVE_BLOGS';

export const REQUEST_ABOUT = 'REQUEST_ABOUT';
export const RECEIVE_ABOUT = 'RECEIVE_ABOUT';

export const CHANGE_PATH = 'CHANGE_SELECTED_PATH';

export const TERMINAL_TYPE = 'TERMINAL_TYPE';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_CATEGORYBLOGS = 'REQUEST_CATEGORYBLOGS';
export const RECEIVE_CATEGORYBLOGS = 'RECEIVE_CATEGORYBLOGS';
